# theme: jekyll-theme-hacker

# Site settings
title: Annals of Uranus
# email: email address
description: >
  Description for site.
baseurl: ""
url: "http://localhost:4000"
github_username: theflowong # creator of site


# Build settings
permalink: pretty
sass:
  sass_dir: _sass
  style: :compressed
